/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.informationsystem;

/**
 *
 * @author paulm
 */
public class DashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashboardForm
     */
    RegistrationForm registerForm = new RegistrationForm();
    RecordForm recordForm = new RecordForm();
    
    public DashboardForm() {
        initComponents();
        
        pnl_Hover1.setVisible(true);
        pnl_Hover2.setVisible(false);
        
        // load Registration Form as the default
        jDesktopPane1.removeAll();
        jDesktopPane1.add(registerForm).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_Tab = new javax.swing.JPanel();
        pnl_Menu1 = new javax.swing.JPanel();
        lbl_Description1 = new javax.swing.JLabel();
        pnl_Menu2 = new javax.swing.JPanel();
        lbl_Description2 = new javax.swing.JLabel();
        pnl_Hover1 = new javax.swing.JPanel();
        pnl_Hover2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Tab.setBackground(new java.awt.Color(30, 56, 100));
        pnl_Tab.setPreferredSize(new java.awt.Dimension(200, 600));
        pnl_Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Menu1.setBackground(new java.awt.Color(30, 56, 100));
        pnl_Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_Menu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_Menu1MousePressed(evt);
            }
        });

        lbl_Description1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_Description1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Description1.setText("DASHBOARD");

        javax.swing.GroupLayout pnl_Menu1Layout = new javax.swing.GroupLayout(pnl_Menu1);
        pnl_Menu1.setLayout(pnl_Menu1Layout);
        pnl_Menu1Layout.setHorizontalGroup(
            pnl_Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Menu1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lbl_Description1)
                .addGap(15, 15, 15))
        );
        pnl_Menu1Layout.setVerticalGroup(
            pnl_Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Description1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Tab.add(pnl_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 50));

        pnl_Menu2.setBackground(new java.awt.Color(30, 56, 100));
        pnl_Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_Menu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_Menu2MousePressed(evt);
            }
        });

        lbl_Description2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_Description2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Description2.setText("RECORDS");

        javax.swing.GroupLayout pnl_Menu2Layout = new javax.swing.GroupLayout(pnl_Menu2);
        pnl_Menu2.setLayout(pnl_Menu2Layout);
        pnl_Menu2Layout.setHorizontalGroup(
            pnl_Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Menu2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lbl_Description2)
                .addGap(40, 40, 40))
        );
        pnl_Menu2Layout.setVerticalGroup(
            pnl_Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Description2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Tab.add(pnl_Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 50));

        pnl_Hover1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_Hover1Layout = new javax.swing.GroupLayout(pnl_Hover1);
        pnl_Hover1.setLayout(pnl_Hover1Layout);
        pnl_Hover1Layout.setHorizontalGroup(
            pnl_Hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnl_Hover1Layout.setVerticalGroup(
            pnl_Hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnl_Tab.add(pnl_Hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 20, 50));

        pnl_Hover2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_Hover2Layout = new javax.swing.GroupLayout(pnl_Hover2);
        pnl_Hover2.setLayout(pnl_Hover2Layout);
        pnl_Hover2Layout.setHorizontalGroup(
            pnl_Hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnl_Hover2Layout.setVerticalGroup(
            pnl_Hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnl_Tab.add(pnl_Hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 20, 50));

        jPanel1.add(pnl_Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 950, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_Menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Menu1MousePressed
        pnl_Hover1.setVisible(true);
        pnl_Hover2.setVisible(false);
    }//GEN-LAST:event_pnl_Menu1MousePressed

    private void pnl_Menu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Menu2MousePressed
        pnl_Hover1.setVisible(false);
        pnl_Hover2.setVisible(true);
    }//GEN-LAST:event_pnl_Menu2MousePressed

    private void pnl_Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Menu1MouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.add(registerForm).setVisible(true);
    }//GEN-LAST:event_pnl_Menu1MouseClicked

    private void pnl_Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Menu2MouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.add(recordForm).setVisible(true);
    }//GEN-LAST:event_pnl_Menu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Description1;
    private javax.swing.JLabel lbl_Description2;
    private javax.swing.JPanel pnl_Hover1;
    private javax.swing.JPanel pnl_Hover2;
    private javax.swing.JPanel pnl_Menu1;
    private javax.swing.JPanel pnl_Menu2;
    private javax.swing.JPanel pnl_Tab;
    // End of variables declaration//GEN-END:variables
}
